spring: #这表示是对spring进行配置
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/emprise #url
    username: root  #用户
    password: lc865422  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #驱动
    name: emprise #数据库名称

  #配置模板引擎
  thymeleaf:
    cache: false
    encoding: UTF-8 #设置编码类型
    servlet:
      content-type: text/html

  #redis配置
  redis:
    host: localhost
    port: 6379
    password: lc865422
    database: 0
    timeout: 5000

  #配置servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#配置站点信息
server:
  port: 8080 # 端口
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: 50MB

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.lvcong.emprise.bean #配置实体类
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个是可以打印sql、参数、查询结果的

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


debug: true